apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-express-rest-api
  name: node-express-rest-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-express-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-express-rest-api
    spec:
      containers:
      - image: shoaibmohmad/node-express-app:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent
        name: node-express-app
        resources:
          # limits:
          #   cpu: 500m
          #   ephemeral-storage: 1Gi
          #   memory: 2Gi
          # requests:
          #   cpu: 500m
          #   ephemeral-storage: 1Gi
          #   memory: 2Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-express-rest-api
  name: node-express-rest-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-express-rest-api
  sessionAffinity: None
  type: LoadBalancer

