apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-express
  name: node-express
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-express
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
      - image: shoaibmohmad/node-express-app:0.0.2.RELEASE
        imagePullPolicy: Always
        name: node-express
        env:
          - name: FLASK_SERVICE_HOST
          #   value: http://python-flask:8100
            valueFrom: 
              configMapKeyRef:
                key: FLASK_SERVICE_HOST
                name: node-express-config-map
        # ports:
        # - name: liveness-port
        #   containerPort: 8000
        # resources: #CHANGE
          # requests:
          #   cpu: 100m
          #   memory: 512Mi
          # limits:
          #   cpu: 500m
          #   memory: 1024Mi #256Mi 
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: liveness-port
        #   failureThreshold: 5
        #   periodSeconds: 10
        #   initialDelaySeconds: 60
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: liveness-port
        #   failureThreshold: 5
        #   periodSeconds: 10
        #   initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-express
  name: node-express
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-express
  sessionAffinity: None
  type: NodePort

