version: '3.7'
services:
  flask-app:
    image: shoaibmohmad/python-flask-app:0.0.2.RELEASE
    ports:
      - "3100:3100"
    restart: always
    networks:
      - express-flask-network

  express-app:
    image: shoaibmohmad/node-express-app:0.0.2.RELEASE
    ports:
      - "3000:3000"
    restart: always
    environment:
      FLASK_SERVICE_HOST: http://flask-app:3100
    depends_on:
      - flask-app
    networks:
      - express-flask-network
  
# Networks to be created to facilitate communication between containers
networks:
  express-flask-network: