apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-flask
  name: python-flask
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: python-flask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - image: shoaibmohmad/python-flask-app:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        name: python-flask
        # ports:
        # - name: liveness-port
          # containerPort: 800
        # resources: #CHANGE
        #   requests:
        #     cpu: 100m
        #     memory: 512Mi
        #   limits:
        #     cpu: 500m
        #     memory: 1024Mi #256Mi 
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: liveness-port
        #   failureThreshold: 5
        #   periodSeconds: 10
        #   initialDelaySeconds: 60
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: liveness-port
        #   failureThreshold: 5
        #   periodSeconds: 10
        #   initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-flask
  name: python-flask
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 3100
  selector:
    app: python-flask
  sessionAffinity: None
  type: NodePort

