apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-02-29T17:32:37Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: python-flask-rest-api
  name: python-flask-rest-api
  namespace: default
  resourceVersion: "17255"
  uid: bdfffeeb-aee1-41e8-93e3-f71817f85551
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.227.203
  clusterIPs:
  - 34.118.227.203
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30319
    port: 8081
    protocol: TCP
    targetPort: 3100
  selector:
    app: python-flask-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.27.160.90
